### ISSUE TITLE
Request to support more configurable wildcard patterns in collections and permissions files

### ISSUE THREAD

**Issue by lifan0127** [marklogic/ml-javaclient-util#120]
New issue created per @rjrudin 's comment here: https://github.com/marklogic-community/ml-javaclient-util/issues/107#issuecomment-520461590

When loading files, we can use a wildcard symbol (*) to specify collections and permissions for all files in a given directories: https://github.com/marklogic-community/ml-javaclient-util/wiki/Loading-files#specifying-collections-and-permissions

However, sometimes it may be convenient to apply the same configuration to all the files in sub-directories as well. Additionally, it may be useful to support filter by file extensions.

This leads to my proposal to support more configurable wildcard patterns similar to `.gitignore` . It will enable virtually any pattern matching and the syntax would be familiar to developers.

https://git-scm.com/docs/gitignore

Examples:

* All JSON files within the current directory: `*.json`
* All JSON files within the current directory and its subdirectories: `**/*.json`.
* All files within "pii" directories anywhere: `**/pii/**`.

**Comment by rjrudin** [comment]
Looks good, thanks.

**Comment by rjrudin** [comment]
Will likely use Spring's AntPathMatcher - https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html - or the Glob support in Java - https://javapapers.com/java/glob-with-java-nio/ .

**Comment by rjrudin** [comment]
@lifan0127 Just a note, I haven't forgotten about this! I'm going to do a 3.14.0 release soon, I'll see how easily I can add this.

**Comment by lifan0127** [comment]
Thank you, @rjrudin . I appreciate very much all the tools you have built to make MarkLogic development a breeze!

**Comment by peetkes** [comment]
This could give a poor man's solution to a simple wildcard pattern matching at the filename level:

```
	protected void processProperties(DocumentFile documentFile, Properties properties) {
		String name = documentFile.getFile().getName();
		if (properties.containsKey(name)) {
			String value = getPropertyValue(properties, name);
			documentFile.getDocumentMetadata().withCollections(value.split(delimiter));
		}
		for(Map.Entry<Object, Object> prop : properties.entrySet()) {
			String key = String.valueOf(prop.getKey());
			if (!key.equals(WILDCARD_KEY) && key.contains(WILDCARD_KEY)) {
				String value = String.valueOf(prop.getValue());
				Pattern pattern = Pattern.compile(key.replace(".","\\.").replace("*", ".*"), Pattern.CASE_INSENSITIVE);
				Matcher matcher = pattern.matcher(name);
				if(matcher.find()) {
					documentFile.getDocumentMetadata().withCollections(value.split(delimiter));
				}
			}
		}
		if (properties.containsKey(WILDCARD_KEY)) {
			String value = getPropertyValue(properties, WILDCARD_KEY);
			documentFile.getDocumentMetadata().withCollections(value.split(delimiter));
		}
	}

```

**Comment by rjrudin** [comment]
Closing this in favor of #173 - aiming to support this soon.
