### ISSUE TITLE
Reload module when running mlWatch and filename case is changed

### ISSUE THREAD

**Issue by jamesagardner** [marklogic/ml-javaclient-util#123]
I'm attempting to standardize some naming conventions on an ml-gradle project.  I have several modules that use an UpperCamelCase naming pattern that I want to replace with a lowerCamelCase naming pattern:

`/service/Object/WriteObject.sjs` -> `/service/object/writeObject.sjs`

I also have renames where only the filename is changed:

`/service/object/WriteObject.sjs` -> `/service/object/writeObject.sjs`

mlWatch is running while both the directory as well as the file renames are performed by my IDE (Intellij IDEA).  When I check the modules database I notice that none of the renamed files are added to the modules database.  Is it possible that the way mlWatch tracks file system changes it skips case-only changes to file names?  Adding a newline and removing a new line causes mlWatch to load the file at the new filename.  The bulk work around is to use `gradlew clean mlWatch` which reloads the modules as expected.

I am on a Cent OS system, so the file system does treat file names as case sensitive.

It would be great if mlWatch cleaned up the old names, but that's already tracked with marklogic-community/ml-gradle#512.

**Comment by rjrudin** [comment]
Tossing "help wanted" on this - really need access to a Windows development environment to test this correctly. Holding off on this for now, as the use case only came up once, and it's easily resolved via "gradle mlReloadModules".

**Comment by jamesagardner** [comment]
One note about `mlReloadModules` in my specific case that wasn't an option since there are other documents in the modules database not managed by ml-gradle.  Running mlReloadModules would have wiped out those un-managed documents, which may or may not be recoverable through any automated means.

**Comment by rjrudin** [comment]
Closing as #133  addressed this.
