### ISSUE TITLE
Support for multiple regex expressions in collections.properties and/or permissions.properties

### ISSUE THREAD

**Issue by peetkes** [marklogic/ml-javaclient-util#196]
I would like for it when the collections.properties and permissions.properties files also aloow for more regular expressions other than exact match or *.
So I would like to be able to specify the following in eg collections.properties:
*=generic-collection
*.xsd=xsd-collection
*.sch=schematron-collection
*catalog.xml=catalog-collection
readme.txt=readme-collection

So the readme.txt would get generic-collection and readme-collection
schema-1.xsd and schema-2.xsd would get generic-collection and xsd-collection
my-catalog.xml and catalog.xml would get generic-collection and catalog-collection

**Comment by rjrudin** [comment]
Tracking internally via MLE-11491. 

Will support glob expressions, not regex's as the existing support is basically a very limited glob expression.
