### ISSUE TITLE
Support for configuring "digestbasic" authentication from gradle.properties

### ISSUE THREAD

**Issue by Marcus-Lind** [marklogic/ml-javaclient-util#205]
Currently, when you try to set `mlJobAuth=digestbasic` in `gradle.properties` and deploy this configuration the below error is returned.

`* What went wrong:
An exception occurred applying plugin request [id: 'com.marklogic.ml-data-hub', version: '5.8.1']
> Failed to apply plugin 'com.marklogic.ml-data-hub'.
   > No enum constant com.marklogic.client.ext.SecurityContextType.DIGESTBASIC`

I confirmed in `com.marklogic.client.ext.SecurityContextType.DIGESTBASIC` that digestsbasic is not an enum. 

In order for an appserver to be compatible with both FastTrack and Data-Hub, the authentication method must be set to `digestbasic`.

**Comment by rjrudin** [comment]
The authentication of the server must be "digestbasic", but that's done via the server JSON payload file. 

The value of at least `mlRestAuth` in ml-gradle (`mlJobAuth` is a DHF-specific property) corresponds to which kind of `SecurityContext` is used in the Java Client. The Java Client does not have a "digestbasic" security context; it must use  either digest or basic. 

If `mlJobAuth` is being used both to select which security context should be used by the Java Client AND also the value of `authentication` in the job server payload file, that's a mistake; it can't be used for both purposes. 

The fix would be in DHF and would involve changing the job server file to have a value of `digestbasic` for the `authentication` field.
